### ISSUE TITLE
Find a more thorough icon provider

### ISSUE THREAD

**Issue by R9295** [R9295/me#25]
@BrainBuzzer , try and find a better icon pack to use for the app UI? You can also remove the inline icon and add it to the label if you see fit, as right now quite a few fields cannot have an inline icon(textareas, selects), it's better to be consistent. 

Also the view headlines use an icon, and I feel it should be more appropriate.

**Comment by BrainBuzzer** [comment]
I think it is fairly straightforward to go with font awesome. Ionicons and material icons do not provide proper brand icons support which is important for us. One option is to use font awesome just for brands, and UIKit icons library for everything else.

**Comment by R9295** [comment]
@BrainBuzzer makes sense. Let's go with font awesome. Start switching and adding new where appropriate
